language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install ."
  - "pip install pytest>=2.4.2 -U"
script: "py.test tests.py"
branches:
  only:
    - master
    - develop
